Fixes and improvements
OpenSemanticLab/osw-python pull request #92
Opened 2024-11-16 09:43 UTC by LukasGold

Aggregated fixes and improvements while developing a tutorial

2024-11-18 10:02 UTC, LukasGold reviewed
@SimonStier: This is a newly introduced module to gather params object in one place and thereby make them easier to access to all users (not only experts)

2024-11-18 10:03 UTC, LukasGold commented on src/osw/types.py
Backward compatibility for python 3.8 to 3.9

2024-11-18 10:06 UTC, LukasGold commented on setup.cfg
pandas requires openpyxl to oven Excel files

2024-11-18 10:07 UTC, LukasGold commented on src/osw/auth.py
Non existing filepaths (which are to be created later on but are defined already) were causing validation error

2024-11-18 10:09 UTC, LukasGold commented on src/osw/data/import_utility.py
Rework to improve usability, and a fix on transform_references causing casting to happen on not yet transformed references when calling super().transform_references() in inheriting helper classes

2024-11-18 10:10 UTC, LukasGold commented on src/osw/express.py
> +    "Property": "Category:Property",  # depends on Entity
Adding Category and Property to make sure that the namespace and title functions in osw.model.static are working as expected.
@SimonStier: Should we create a mechanism to ensure installed dependencies other than in osw.express?

2024-11-18 10:11 UTC, LukasGold commented on src/osw/express.py
> +            caller_globals[ti.class_name] = getattr(
WIthout forcing the globals() from the most outer namespace to be passed to the function, the imported modules would only be available within osw.express namespace

2024-11-18 10:12 UTC, LukasGold commented on src/osw/express.py
> +    file_io: Optional[Union[TextIO, TextIOWrapper, None]] = None
Was causing validation errors when method open() was called

2024-11-18 10:14 UTC, LukasGold commented on src/osw/model/static.py
> +
Functionality hat to be moved back to functions from methods to be applicable to Python classes as in one of the tests

2024-11-18 10:15 UTC, LukasGold commented on src/osw/ontology.py
> +                    e.subclass_of.append(self.import_config.meta_class_title)
was causing validation errors on assignment

2024-11-18 10:15 UTC, LukasGold commented on src/osw/params.py
Basically a convenience module -> An idea for better UX

2024-11-18 10:16 UTC, LukasGold commented on src/osw/types.py
> +class FilePath(PydanticFilePath):
A way to avoid validation errors on not (yet) existing filepaths
@SimonStier: Maybe rename class? Maybe add docstring?

2024-11-18 10:17 UTC, LukasGold commented on src/osw/types.py
> +    NoneType = type(None)
Backward compatibility for python 3.8 to 3.9

2024-11-18 10:18 UTC, LukasGold commented on src/osw/utils/wiki.py
For compatibility with existing code

2024-11-18 10:19 UTC, LukasGold commented on src/osw/wtsite.py
> +    class SearchParam(wt.SearchParam):
Adding SearchParam where it is used -> better UX

2024-11-24 06:23 UTC, simontaurus requested changes
I guess all changes are included in https://github.com/OpenSemanticLab/osw-python/pull/89, see suggestion there

2024-11-24 06:23 UTC, simontaurus commented on src/osw/core.py
> +                        remove_empty_strings(jsondata)
Should be remove_empty including [] and {} (see other pull request)

2024-11-24 06:23 UTC, simontaurus commented on src/osw/custom_types.py
> +class FilePath(PydanticFilePath):
consider renaming to "PossibleFilePath", see other pull request

2024-11-24 06:23 UTC, simontaurus commented on src/osw/model/entity.py
> +    def __init__(self, **data):
consider moving to OswBaseModel, see other pull request

2024-11-26 09:39 UTC, merged